sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t asg0828/docker-react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true asg0828/docker-react-app npm run test -- --coverage

after_success:
    - ehco "Test Success"
